### ISSUE TITLE
Cant use Cardano metadata on NFTmakerpro

### ISSUE THREAD

**Issue by glassbrickstudio** [torrinworx/Blend_My_NFTs#103]
1. Please make the json metadata file names correspond to the images filenames 

![2](https://user-images.githubusercontent.com/55618307/167419542-14f42a87-559b-4502-85fa-b6cf9e8abb6a.jpg)

2.   the placeholder for "image" and "mediatype" is blank please include it like "<policy_id>":   

"image": "<ipfs_link>",
"mediaType": "<mime_type>",

**Comment by torrinworx** [comment]
It's pretty easy to change, just go into `Exporter.py` for the file naming and `Metadata.py` for the metadata format. Just a matter of messing around with dictionaries and strings.

**Comment by glassbrickstudio** [comment]
just wanted it as default.. thanks

fixed "image": "<ipfs_link>",
"mediaType": "<mime_type>",
