### ISSUE TITLE
Logic not working at all

### ISSUE THREAD

**Issue by f4ww4z** [torrinworx/Blend_My_NFTs#106]
I'm trying to implement logic in the Logic example project (and if working I will try on my project), so I created the json file like this:

```json
{
  "Rule-1": {
    "Items-1": ["Red Cube_1_25"],
    "Rule-Type": "Only With",
    "Items-2": ["Red Sphere_1_25"]
  },
  "Rule-2": {
    "Items-1": ["Black Cube_1_25"],
    "Rule-Type": "Only With",
    "Items-2": ["Black Sphere_1_25"]
  },
  "Rule-3": {
    "Items-1": ["Blue Cube_1_25"],
    "Rule-Type": "Only With",
    "Items-2": ["Blue Sphere_1_25"]
  },
  "Rule-4": {
    "Items-1": ["White Cube_1_25"],
    "Rule-Type": "Only With",
    "Items-2": ["White Sphere_1_25"]
  }
``` 

Theoretically this should only be able to generate 4 NFTs, and for each nft the cube and sphere should be the same color. So I ran with this config:

![image](https://user-images.githubusercontent.com/21199242/169246577-d18721fe-78b8-40a4-90c2-7dfe8517e720.png)

but the results does not follow the rules given. Here's an example of generated `Data_Logic Test_1.json`:

```json
{
 "name": "Logic Test_1",
 "NFT_DNA": {
  "2-1": {
   "Complete": false
  }
 },
 "NFT_Variants": {
  "Cube": "Blue Cube_2_25",
  "Sphere": "Red Sphere_1_25"
 }
}
``` 
`Data_Logic Test_2.json`:
```json
{
 "name": "Logic Test_2",
 "NFT_DNA": {
  "1-4": {
   "Complete": false
  }
 },
 "NFT_Variants": {
  "Cube": "Red Cube_1_25",
  "Sphere": "White Sphere_4_25"
 }
}
```

I wonder if the logic.json file I passed in gets read at all? Thanks

**Comment by f4ww4z** [comment]
@torrinworx any solution to this?

**Comment by torrinworx** [comment]
Hmmmm, yeah this is really weird behaviour, I don't really understand why this is happening. I'm planning on revamping the Logic system so its just a simple 'If' 'Then' system. If this Attribute/Variant is selected Than Always/Never allow this list of Attributes/Variants to appear etc.

**Comment by torrinworx** [comment]
What version of BMNFTs are you using btw?

**Comment by f4ww4z** [comment]
@torrinworx I'm using the latest version (download master branch as zip). `3.1.0`

**Comment by f4ww4z** [comment]
I also tried version `2.1.0` ([before you removed the `Logic example.blend` file](https://github.com/torrinworx/BMNFTs_Examples/tree/befc43af4b17b277706ae29fa647880754c0e4fd)) but still the logic is not working.

**Comment by torrinworx** [comment]
I'm going to close this for now as I plan on revamping Logic with a new system in the near future. Please stay tuned for updates in our Discord server. Thank you for bringing this to my attention
