### ISSUE TITLE
DNA no rarity, need to generate exact amount

### ISSUE THREAD

**Issue by ultraviolet007rainbow** [torrinworx/Blend_My_NFTs#108]
Hi,

We are trying to generate an exact number of NFTs and the maximum is the correct number, but the suggested is half of that. There is no rarity, we have a specific purpose and when we generate the DNA it creates all the DNA with no duplicates confirmed using Excel. However it is one short, so if we wanted to generate a total of 3000 unique with no rarity, it suggests 1500, and then only outputs the DNA for 2999. How can we get this system to generate all 3000 exactly?

Thank you :)

**Comment by ultraviolet007rainbow** [comment]
Just noticed a disparity, the Batch Data folder has the full number of JSON files we need but the DNA in NFTRecord.json is 2 short. Does that mean there are duplicates in the Batch_Data folder which has the full number of JSON files? Why the disparity?

**Comment by torrinworx** [comment]
Hi there @ultraviolet007rainbow, Blend_My_NFTs is a very probabilistic system to save on generation time. To get exactly 3000 you would need at least 6,000 thousand possible combinations. If you'd like to read more about why this is, I've explained it in as much detail as I can in this section of the docs:

https://github.com/torrinworx/Blend_My_NFTs#notes-on-rarity-and-weighted-variants

**Comment by torrinworx** [comment]
You are most likely seeing this behaviour because you are trying to generate a certain number of NFTs that is very close to your maximum number of combinations which our team doesn't recommend.
