### ISSUE TITLE
Render animation to image sequence instead of MP4 or AVI?

### ISSUE THREAD

**Issue by ultraviolet007rainbow** [torrinworx/Blend_My_NFTs#109]
Hi,

Is there a way we can render animations out to PNG image sequences, if not can you please implement that as an option?
Not sure why AVI is even being used, and I find it odd in general that AVI is supported in any way by Blender. If anything ProRes would be a much better option here. Do people still use AVI files? I haven't even seen an AVI file since the 90s, Macs don't support it. Does Windows still support AVI?

Anyway, PNG image sequence output of animations would be excellent.

Thank you :)

**Comment by torrinworx** [comment]
This will be added with a pull request to the V4 Alpha: https://github.com/torrinworx/Blend_My_NFTs/pull/105
