### ISSUE TITLE
No module named 'Blend_My_NFTs-3'

### ISSUE THREAD

**Issue by jzgdev** [torrinworx/Blend_My_NFTs#114]
![image](https://user-images.githubusercontent.com/6233998/170910730-88baf679-b7ca-4db1-bdae-e1271b6c13e0.png)

**Comment by jzgdev** [comment]
On Windows 10. Blender Version: 2.8.13

**Comment by torrinworx** [comment]
Blend_My_NFTs only supports Blender versions 3.0.0+, I recommend upgrading the a newer version.

**Comment by jzgdev** [comment]
Ahh thank you for the help and I apologize for the unnecessary issue being opened. Appreciate your patience.

**Comment by torrinworx** [comment]
@jzgdev Oh no worries! Please feel free to re-open the issue if you still experience the error and let me know if you have any further questions!

**Comment by jzgdev** [comment]
I updated to the latest version of blender and was getting the same issue :/ any advice tips to point me in the right direction?

**Comment by torrinworx** [comment]
@jzgdev Make sure you have uninstalled all older versions of Blend_My_NFTs before updating. Otherwise please send the error code and a screen shot
