### ISSUE TITLE
Please post some screenshots

### ISSUE THREAD

**Issue by bitcoinmeetups** [torrinworx/Blend_My_NFTs#12]
Hello,

I'm MB. A very nice and polite guy.

Please post some screenshots.

**Comment by torrinworx** [comment]
I added a link to the youtube tutorial in the readme.md file.

**Comment by torrinworx** [comment]
@bitcoinmeetups is there a specific feature you would like there to be images of in the the tutorial page?

**Comment by bitcoinmeetups** [comment]
An example of 3D images that you have generated would be good

**Comment by torrinworx** [comment]
Added some images to the readme.md file as well as a link to the youtube tutorial.

**Comment by bitcoinmeetups** [comment]
Still cannot see any actual images of the creative output. I mean colorful 3D artwork and such. I suggest finding some screenshots of that and putting it at the top of the readme.md.

I read fast but it's better to catch the interest of the reader with some snazzy imagery right at the top.

By the way, do you have some NFT's for sale? I buy anything, pay with ASTRAL.

-------- Original Message --------
