### ISSUE TITLE
Blender should save before Generating NFTs to preserve current state of Blender file

### ISSUE THREAD

**Issue by torrinworx** [torrinworx/Blend_My_NFTs#120]
I feel like this should be like a checkbox setting in the "Other" tab instead of a default enabled thing. As there might be issues where people are just testing things out and don't want to save progress on their Blender file.

But it should be there for more serious design work I guess. I'll probably do a poll tomorrow in the Discord, we'll see....

**Comment by memoo55** [comment]
Compliance with this choice everything should be left to the user

**Comment by torrinworx** [comment]
Feature added to this commit: https://github.com/torrinworx/Blend_My_NFTs/commit/3cb2a69c81932e5b882b69c4c4bfbdd153a2dfee

Will be merged once Material Randomizer and Logic implementation is stable. Thanks for the input @memoo55!
