### ISSUE TITLE
Rendering headlessly on Google Colab with logic enabled

### ISSUE THREAD

**Issue by shadyaymn** [torrinworx/Blend_My_NFTs#128]
I try to run headless on colab but keep running into an error.

Firstly I configured the config.cfg file to change the path of the materialFile to whatever it is on drive i.e /content/drive/MyDrive
I noticed that there isn't a logicFile in the config.cfg file so my initial thought was that disabling logic would make it work which it did. I tried changing the logicFile path and the enable_Logic_Json to be true as well in the __init.py__ file but I could not get it to work as I did not write the code and don't completely understand it. So I think there needs to be an enable_Logic_Json and logicFile in the config.cfg file so the user can change them.

**Comment by torrinworx** [comment]
The headless functionality hasn't been maintained with the newer updates, I would recommend going back to the commit when it was first introduced for Google Colab.

**Comment by shadyaymn** [comment]
> But this would cause the material rarity to not work because it was only recently fixed right?

**Comment by torrinworx** [comment]
This issue should be solved according to @matt-159 with the latest pull.
