### ISSUE TITLE
Remove + 1, else issues arise with material index mismatch. 

### ISSUE THREAD

**Issue by torrinworx** [torrinworx/Blend_My_NFTs#139]
https://github.com/torrinworx/Blend_My_NFTs/blob/db4e4c21c1fd3ba33578b6f4892bcbbd0ee31303/main/Material_Generator.py#L112

I honestly don't know why, but just remove this and it works for some reason. That's it. Add it to the newest update soon.

**Comment by torrinworx** [comment]
In all seriousness it causes a keying error in the Exporter.py file on this line: https://github.com/torrinworx/Blend_My_NFTs/blob/db4e4c21c1fd3ba33578b6f4892bcbbd0ee31303/main/Exporter.py#L208

**Comment by torrinworx** [comment]
I believe this is something to do with the change from an collection order number name based sorting system to a purely index based sorting system for the materials in a given material list from the materials file. Not too sure though.

**Comment by ethangale25** [comment]
What are the current implications with this current issue?  Will the metadata not match the rendered result?

**Comment by torrinworx** [comment]
@ethangale25 from my testing it seems like it miss aligns the textures to their order number by incrementing it creating a non existent material for no reason, or at least non that I can remember. Later on in the Exporter it then tries to query the material list and results in an IndexError in the event that the index is larger than the list.

**Comment by ethangale25** [comment]
@torrinworx -
Thanks for your quick response and explanation!  
Version 4.5.0 is amazing... thanks for all of your hard work on this project; - you have thousands of people rooting for you as you lug away behind your computer. Cheers mate.

**Comment by torrinworx** [comment]
@ethangale25 Np! Thank you for the kind words, that means a lot to me ♥
