### ISSUE TITLE
Material selection bug (Off-by-one)

### ISSUE THREAD

**Issue by Knockturnal** [torrinworx/Blend_My_NFTs#145]
Hi,

When selecting materials the add-on will choose a random material from your provided JSON file and use that for your output image. If it can not match your variant to an entry in the materials JSON file, then it will return a 0, which means "do not change the material". This makes perfect sense of course, but it leads to a bug:

When the add-on is selecting a material at random, it can, completely organically, choose index 0. This means that the material will not be changed, an unpredictable and unwanted behavior.

Later, the add-on will generate the images based on the DNA, but because 0 is ignored it subtracts 1 when doing the material look-up. This means that when it has chosen 0 it will use whatever material was last assigned to that variant, and all other materials down the list will be shifted one space down. The last material in the list will never be rendered. 

If the add-on chooses, say, material 6/6 (of an index 0 list), it will then subtract 1 before changing the materials in the generation step making it display as 5/6. If it chooses 0/6 then it will not change the material, and it will use the one that was applied for the last generation.

Example materials.json:

```json
"Cube_0_40": {
	"Material List": {
		"Green": 0,
		"Red": 0,
		"Yellow": 0,
		"Purple": 0,
		"Magenta": 0,
		"Shiny": 0,
		"Swirly": 0
		},
		"Variant Objects": []
	},
```

If "Green" is chosen, it will not change the material and use whatever was last applied. If "Red" is chosen, it will be displayed as "Green", and so on. If "Swirly" was chosen, it will display as "Shiny", but nothing can ever display as "Swirly".

This could create an output like:

```
======== Generating NFT 1/5: TestCollection_6 ========
Variants selected:
{'BG': 'BG_0_100', 'Base': 'Sphere_1_25'}

Materials selected:
{'BG_0_100': 'Purple', 'Sphere_1_25': '0'} <- It incorrectly assigns material 0

DNA Code:0-1:4-0
```

It must have been [this recent fix](
https://github.com/torrinworx/Blend_My_NFTs/commit/17b3fcf1a06a3e65ae9c42b87833f324507b8997) that introduced this bug, and it's typical that I had to do such a deep dive to identify the problem when it was so recently introduced. Oh well.

Also[ see my PR](https://github.com/torrinworx/Blend_My_NFTs/pull/144)  #144 a fix (more or less reverting the change above)

**Comment by ethangale25** [comment]
AWESOME!! Thanks @Knockturnal

**Comment by torrinworx** [comment]
Will investigate further, related to issue #139.
