### ISSUE TITLE
Large file size problem

### ISSUE THREAD

**Issue by Prasanth98769865876578** [torrinworx/Blend_My_NFTs#156]
Our blender size exceeds way beyond 5gb limit specified in document. The document mentions "recommended".
Is 5gb a hard limit, or can we go beyond 5gb. @torrinworx .

**Comment by cjwmaya** [comment]
你好，我是也毛儿，信件已经收到，

**Comment by torrinworx** [comment]
It's a soft limit, it's really just dependent on how much RAM and VRAM your system has.

**Comment by cjwmaya** [comment]
你好，我是也毛儿，信件已经收到，
