### ISSUE TITLE
Integrate with Google Colab

### ISSUE THREAD

**Issue by slavakurilyak** [torrinworx/Blend_My_NFTs#39]
Please consider integrating your project with Google Colab which currently supports max render time of 12 hours and idle time out at 90 minutes. 

For inspiration, check out Micro Singularity's [Github repo](https://github.com/microSingularity/blenderGoogleGPU) and [YouTube video](https://www.youtube.com/watch?v=A8FiCPUEv9Q) showing how to use the repo.

Keep up the great work at This Cozy Studio!

**Comment by torrinworx** [comment]
I don't really have the time to look into this at the moment, but that's an interesting request I'll leave it here to remind me when I have the time to deep dive or if a community member wants to take up the challenge.

**Comment by torrinworx** [comment]
Reopening this issue to investigate potential integration with future projects.

**Comment by torrinworx** [comment]
This is now possible with the latest merge from @TheBrochacho!
