### ISSUE TITLE
Enable rarity for external 3d Models

### ISSUE THREAD

**Issue by L-TheG** [torrinworx/Blend_My_NFTs#41]
Hi,
I already wrote a script that mostly covers this. The folder structure just has to be exactly the same as you already laid out in the readme.
You just postfix the rarity to filenames of the external 3d models to enable rarity.

After that setup, just import those files into a scene while keeping to the .blend scene collection structure reuqired for the main script. (The scene collection structure is mirrored by the folder structure for the external 3d models anyway).

After that you can simply run your main script and use it normally.

My importer script is extremely messy as I have never worked with the blender API and not well integrated into you scripts. So currently you have to load the importer script and run it before loading the main.py script.

I dont have much time to rewrite this currently. Just let me know if youd rather implement this yourself or if you're ok with waiting a few weeks for me to commit the cleaned up, more integrated importer.

cheers.

**Comment by torrinworx** [comment]
Hi @L-TheG, 

Feel free to make a pull request! I can probably sit down and integrate the script you have created so far myself sometime this week. That would be a huge help, thank you so much! 🙂
