### ISSUE TITLE
Support for Maxon Cinema 4D

### ISSUE THREAD

**Issue by slavakurilyak** [torrinworx/Blend_My_NFTs#42]
It would be great to see BlendMyNFTs expand to support [Maxon Cinema 4D](https://www.maxon.net/en/cinema-4d). Here's the [official Cinema 4D Python examples](https://github.com/PluginCafe/cinema4d_py_sdk_extended). Here's the [Python SDK](https://developers.maxon.net/docs/Cinema4DPythonSDK/html/index.html).

**Comment by torrinworx** [comment]
We'll take a look at this in the future after BMNFTs is stable and has more features 👍
