### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by thecosss** [torrinworx/Blend_My_NFTs#49]
I've got this error in the system console, how can I solve it? I'm on mac

**Comment by renekendeins** [comment]
Give more info please. Are you executing the script from the Blender Scripting tab? And is your .blend file in the root of Blend_My_NFTs folder?

**Comment by thecosss** [comment]
Yes, the problem was in file location, I've started the script with the default cube :)
But now I have another problem. I tried to generate example 10 nfts with 5 per batch. And it stuck on generating. Folder NFT_Output is empty.
