### ISSUE TITLE
What is the best practice to render on multiple machines?

### ISSUE THREAD

**Issue by thecosss** [torrinworx/Blend_My_NFTs#50]
So I've generated 2 batches and want to render them on 2 machines. How to do it without generating DNAs again?

**Comment by torrinworx** [comment]
The best practice is to duplicate the Blend_My_NFTs-main folder and send it to however many machines you have. Run the initial step on one machine; You should now have all the ``Batch#.json`` files generated in the ``Batch_Json`` folder. 

Send however many batches you want to each machine and render as you would on one machine. This ensures that each machine follows the ``NFTRecord`` and doesn't generate duplicate NFTs. After all the images are generated, send each ``Batch#`` folder to the main computer. Then run the final step ``reconfigureBatches`` to combine them all into one ``Complete_Collection`` folder containing whatever metaData you have generated. 

Hope this Helps!

**Comment by thecosss** [comment]
Thank you, very helpful. I want to clarify some things. After I sent batches to other machines. what settings do I need to render without generating?
