### ISSUE TITLE
Cardano MetaData

### ISSUE THREAD

**Issue by sahirjutt20** [torrinworx/Blend_My_NFTs#52]
Hello Dear Developers!
I appreciate your hard-work and its a great help!

I am facing the issue in metadata output that there is rarity number and item number in hierarchy which should not be there so kindly make it easy and remove that numbers. see attachments for reference

Current Issue
![image](https://user-images.githubusercontent.com/91593993/152019290-947a41b6-d40e-4b1d-b0bd-7f125dde9aa0.png)

Need Correction like following:
![image](https://user-images.githubusercontent.com/91593993/152019584-0df92fc8-ccb0-41bb-98c1-77bd5348ce01.png)

  if that happens then I can easily upload my metadata on NFT Maker Pro. thanks in advance

**Comment by torrinworx** [comment]
This issue can be resolved with the ``turnNumsOff`` bool variable in the config.py file, in the new BMNFTs UI Edition this feature is permanently set to true so the numbers never appear.
