### ISSUE TITLE
Shouldn't the content of the NFT_Output folder be in .gitignore?

### ISSUE THREAD

**Issue by cha-hin** [torrinworx/Blend_My_NFTs#58]
Hello,

In my opinion, the generated batches in the `NFT_Output` folder unnecessarily pollute the git tracking system.

I suggest adding the following line to the `.gitignore` file.

```
NFT_Output/*
```

Thank you.

**Comment by torrinworx** [comment]
Are you referring to the version 1 of Blend_My_NFTs? The new Blend_My_NFTs UI Edition is setup so that you can choose a save path directory and all the folders are dynamically created there.

**Comment by cha-hin** [comment]
My bad, I was indeed referring to the prevous version of Blend_My_NFTs. 

So in this new version, I presume it can't be done the old way anymore, right? (I used to run my script from the command line, I found that very convenient).

**Comment by torrinworx** [comment]
Yeah in the new version you get to choose a save path, so there is no need to have it in the repo anymore.
