### ISSUE TITLE
Unable to install addon in blender 3.0 stable

### ISSUE THREAD

**Issue by InfinityCg** [torrinworx/Blend_My_NFTs#60]
Upon enabling the addon, I encounter this error

Traceback (most recent call last):
  File "I:\Blender Versions\stable\blender-3.0.0+stable.f1cca3055776\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Blend_My_NFTs-2'

**Comment by torrinworx** [comment]
Hi there, 

It looks like you have multiple instances of Blend_My_NFTs installed on your computer. Try uninstalling all versions of the add-on and do a fresh install. 

Hope this helps, 

Torrin

**Comment by InfinityCg** [comment]
Hello torrin!
Thanks for the reply

I have tried uninstalling it from preferences and the deleted every folder related to addon in Roaming>Blender foundation folder still it is giving the same error
I tried using different blender versions but same, am I doing something wrong

Again, thanks for helping out

**Comment by LubomirKurpel** [comment]
Hello, I have the same error when trying to install at Blender 3.0.1

I must however say that I was experimenting with Blend my NFTs in november / december where there was no stable release and I was loading .py files manually. Maybe this screwed up my installation?

**Comment by LubomirKurpel** [comment]
I think I have found a solution. The version it did not work with was Blend_My_NFTs-2.0.0 but when downloading via "get code" button and zipping into Blend_My_NFTs-main.zip it works!

Cheers! Thanks a lot!

**Comment by InfinityCg** [comment]
> I think I have found a solution. The version it did not work with was Blend_My_NFTs-2.0.0 but when downloading via "get code" button and zipping into Blend_My_NFTs-main.zip it works!
> 
> Cheers! Thanks a lot!

This worked!
Thanks a great lot, really appreciate it
