### ISSUE TITLE
Generate NFTs button calls up a python traceback error

### ISSUE THREAD

**Issue by aikkoo** [torrinworx/Blend_My_NFTs#62]
![issue](https://user-images.githubusercontent.com/78805370/155855617-45bd1a51-5f73-4d82-aeca-afbef4293c46.PNG)

**Comment by torrinworx** [comment]
Hi there, please checkout our Discord server for help! We have faster response times over there and we don't answer technical support on our GitHub page. 

It looks like you have an issue with your .blend file naming conventions, read the following documentation for more details: 
https://github.com/torrinworx/Blend_My_NFTs#blender-file-organization-and-structure

If that doesn't solve your issue then you may have made changes to your .blend file and forgot to re-create the NFT data: 
https://github.com/torrinworx/Blend_My_NFTs#step-1---create-nft-data

Hope this helps!
