### ISSUE TITLE
Remove Watermark

### ISSUE THREAD

**Issue by norfolkpine** [torrinworx/Blend_My_NFTs#69]
What are the steps to remove the  "The Cozy Place" watermark from output images in the Cozy Place Example file.

**Comment by torrinworx** [comment]
The watermark is only present on the example .blend file provided with the tutorial. Blend_My_NFTs does not place a watermark on your content. 

We encourage you to create your own .blend file and artwork, we place the watermark there to prevent scams and to protect our community.
