### ISSUE TITLE
octane

### ISSUE THREAD

**Issue by leonepietrantonio** [torrinworx/Blend_My_NFTs#70]
Works perfectly with eevee and cycles, but crashes when using octane as render engine. Any way to solve this?

**Comment by torrinworx** [comment]
As far as I'm aware, Octane isn't a very stable engine atm. Members of our community have had some success running it, however from what I've heard it doesn't always work. 

I haven't looked into it and I really wouldn't know anyway to make it compatible and stable.

If you have any suggestions please feel free to let me know, I'll leave this ticket open for further research.
