### ISSUE TITLE
Rename and Refactor Partial Collection

### ISSUE THREAD

**Issue by ethangale25** [torrinworx/Blend_My_NFTs#75]
Hey Torrin!

Is there any way that a not-fully-rendered-collection could be renamed/refactored with the metadata in order to have a sequenced release of an NFT collection? Example would be renaming/refactoring per batch.

I ask because in the case of video NFTs, render time is LONG (potentially hundreds of times longer duration) and breaking down the finalization of a chunk of the collection could prove very useful.

Forgive my ignorance if this has already been implemented, but according to the documentation, It seems that an entire collection must be rendered prior to renaming/refactoring.

Thank you for all of your hard work.

**Comment by torrinworx** [comment]
Ahhhh.... there isn't a way to do it with vanilla BMNFTs. However you could modify it quite easily to do what you describe. I'd suggest looking at the Batch_Sorter.py and Exporter.py files, they handle the batch distribution and the rendering respectively. 

If it's just refactoring and generating the metadata then look at the refactorer.py file. You can only generate them after all the files have been rendered, however you could take the functions in that file and rig them to trigger after each render. It would be a lot of work tbh but it's doable if you know your way around Python.
