### ISSUE TITLE
Generate and Data Error

### ISSUE THREAD

**Issue by theknowbody** [torrinworx/Blend_My_NFTs#84]
![Screen Shot 2022-04-11 at 12 05 02 PM](https://user-images.githubusercontent.com/103445867/162787492-3a2ad5e0-f87a-4238-824f-9dceca4c48a0.png)
![Screen Shot 2022-04-11 at 12 14 01 PM](https://user-images.githubusercontent.com/103445867/162787510-46fc2387-cc02-455c-9541-b1e45a0b6265.png)

i dont know what to do

**Comment by ethangale25** [comment]
You are missing an underscore on Shibainu Gold Collar

"Shibainu Gold Collar 11_9" --> "Shibainu Gold Collar_11_9"

**Comment by torrinworx** [comment]
I believe this was solved earlier in the Discord as well. Feel free to re-open if the issue persists, but it looks like a simple naming issue.
