### ISSUE TITLE
When I try to generate the data for the NFTS I get this error

### ISSUE THREAD

**Issue by alexjshepler** [torrinworx/Blend_My_NFTs#88]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/19987488/163249979-2c2dc9d7-1e3c-4f24-8bd3-c510ad7ae25c.png">

**Comment by alexjshepler** [comment]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/19987488/163252430-4a8e8559-e7fb-4f9d-824d-f123325fe936.png">

And everything follows that formatting

**Comment by alexjshepler** [comment]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/19987488/163252532-1417452e-6927-4b11-b47a-11ac85d8fdf5.png">

(I did go through and find someone that had the same issue that I was having and found that taking out the spaces worked for him and I did that and I'm still having the same issure. Here is an updated error as well)

**Comment by ethangale25** [comment]
Your collections need to be renamed to very specific values. See the link below to see the naming conventions that yours needs to follow:
[https://github.com/torrinworx/Blend_My_NFTs#blender-file-organization-and-structure](url)

An example of what your collections should look like are the following:
Blue Icing_1_
Red Icing_2_15
Yellow Icing_3_15
etc.

**Comment by ethangale25** [comment]
If the above link doesn't work, just go to the main README page and scroll down to the "Blender File Organization and Structure" section. There you will find details

**Comment by alexjshepler** [comment]
Thank you, I'll try that
