### ISSUE TITLE
Stopped mid generation and gave me this error

### ISSUE THREAD

**Issue by alexjshepler** [torrinworx/Blend_My_NFTs#90]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/19987488/163274835-18f681c3-ec7c-4fc5-8bc2-2ae8d160ad09.png">

**Comment by torrinworx** [comment]
It looks like you made changes to your .blend file after you created your NFT data. Try re-creating the NFT data then start generating again.

**Comment by alexjshepler** [comment]
I've done that. Even went as far as going and deleting the previous data files then regenerating them then trying it again then walking away from my computer

**Comment by torrinworx** [comment]
Could you send a screenshot of your Blender Scene? It's possible you have an attribute/variant collection that is not named properly.

**Comment by alexjshepler** [comment]
Everything should be named correctly. I went thought that issure already and when it wasn't it wouldn't even let me make the data for it

<img width="345" alt="image" src="https://user-images.githubusercontent.com/19987488/163283806-e9a8bb22-0534-4fa7-9130-94829625b3ca.png">

**Comment by torrinworx** [comment]
Oh so for the number order after the first underscore, don't include the extra zero. That might be the issue

**Comment by alexjshepler** [comment]
Alright. I will try that

**Comment by torrinworx** [comment]
I'm going to close this issue for now, please re-open if you still experience the issue.
