### ISSUE TITLE
set image url in metadata

### ISSUE THREAD

**Issue by ZigBalthazar** [torrinworx/Blend_My_NFTs#97]
hi
i try to refactor and export metadata but in .json files the "image" section is empty
i try to change the metadata.py file and its work to input for example <baseURL>+<imageName>+<.png> to set "image" in metadatas

please add a baseUrl in this generator to set image url automatically

Thanks

**Comment by lukaiaa** [comment]
Can you show me changed script? I have same problem

**Comment by ZigBalthazar** [comment]
in `main/Metadata.py` change this part of code = 
```
# ERC721 Template
def returnErc721MetaData(name, NFT_DNA, NFT_Variants, custom_Fields_File, enableCustomFields, erc721_description):
    metaDataDictErc721 = {
        "name": name,
        "description": erc721_description,
        "image": "",
        "attributes": None,
    }
```

for example to = 

```
# ERC721 Template
def returnErc721MetaData(name, NFT_DNA, NFT_Variants, custom_Fields_File, enableCustomFields, erc721_description):
    metaDataDictErc721 = {
        "name": name,
        "description": erc721_description,
        "image": "BaseURI"+name,
        "attributes": None,
    }
```

you should make your customize URI in "image" field

**Comment by ZigBalthazar** [comment]
> Can you show me changed script? I have same problem



in `main/Metadata.py` change this part of code = 
```
# ERC721 Template
def returnErc721MetaData(name, NFT_DNA, NFT_Variants, custom_Fields_File, enableCustomFields, erc721_description):
    metaDataDictErc721 = {
        "name": name,
        "description": erc721_description,
        "image": "",
        "attributes": None,
    }
```

for example to = 

```
# ERC721 Template
def returnErc721MetaData(name, NFT_DNA, NFT_Variants, custom_Fields_File, enableCustomFields, erc721_description):
    metaDataDictErc721 = {
        "name": name,
        "description": erc721_description,
        "image": "BaseURI"+name,
        "attributes": None,
    }
```

you should make your customize URI in "image" field

**Comment by lukaiaa** [comment]
Thank You! this helped me a lot.

**Comment by sandhunter66** [comment]
can you show me the example? im quite new to this and i can see the image part is empty.. what example of baseuri format should be in there?and what is ++name is about?

**Comment by ZigBalthazar** [comment]
> can you show me the example? im quite new to this and i can see the image part is empty.. what example of baseuri format should be in there?and what is ++name is about?

Hi @sandhunter66 

you can use my  "Blend_My_Nfts" fork
add it to Blender and use it easily,
in "Refactor and Metadata" sections, this fork have two additional input,
1. BaseUri == fill it with json metadata Base uri example : "ipfs://xxxxxxxxxxxxxx"
2.  NFT Media Format, example : "PNG"

and after that refactor the metadata...

Fork == https://github.com/ZigBalthazar/Blend_My_NFTs
Fork details == https://github.com/torrinworx/Blend_My_NFTs/pull/102

**Comment by sandhunter66** [comment]
hi..thank you..i have install the fork and i can see the baseuri input area.i want to ask if i already start generate 5000 nft with 100 per batch using original BMFT, it i install the fork can i just continue or i need to generate the nft from the beginning?

**Comment by ZigBalthazar** [comment]
> hi..thank you..i have install the fork and i can see the baseuri input area.i want to ask if i already start generate 5000 nft with 100 per batch using original BMFT, if i install the fork can i just continue or i need to generate the nft from the beginning?

Hi
this plugin read data from data generator section(generate unique DNA etc...)
if you generate NFTs and have the datas in data generator section you can use refactor and generate metadatas

**Comment by sandhunter66** [comment]
hi..since im not finish generate the 5000 nft when i install the fork i need to regenerate the data.. when i recheck the data for previous batch it is not the same because i regenerate it.. but its ok.. i can start from beginning..overall it works!! thank you so much!! it is so helpful
